packages:
  - packages/*
  - backend
  - frontend
  - queueConsumer
  - docs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - cpu-features
  - esbuild
  - msgpackr-extract
  - protobufjs
  - ssh2
  - vue-demi

overrides:
  '@nestjs/common@<10.4.16': '>=10.4.16'
  esbuild@<=0.24.2: '>=0.25.0'
  got@<11.8.5: '>=11.8.5'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  tmp@<=0.2.3: '>=0.2.4'
