server {
    listen 80 default_server;

    # Serve the built VitePress docs
    root /usr/share/nginx/html;

    # Serve VitePress from the root URL
    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
