name: Check Migrations

on:
    pull_request:
        branches:
            - main

jobs:
    check-migrations:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
              working-directory: backend

            - name: Check migrations
              run: pnpm run migration:check
              working-directory: backend
