on:
    push:
        branches: ['dev']
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - dev

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Generate Build Info
              run: bash create_build_info.sh
              working-directory: frontend

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.x'

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Run pre-commit
              run: pre-commit run --all-files --show-diff-on-failure
              env:
                  SKIP: eslint,prettier

            - name: Prepare Quasar
              run: pnpm exec quasar prepare
              working-directory: frontend

            - name: Type Check
              run: pnpm run type-check

            - name: Lint Check
              run: pnpm run lint:check

            - name: Run Prettier Check
              run: pnpm run prettier:check
